"use client";

/**
 * Phosphor Light icon re-exports - the SERVER-component-safe boundary.
 *
 * `@phosphor-icons/react` calls `React.createContext` at module top-level
 * (for its IconContext). When a server component imports phosphor directly,
 * that top-level code runs in the server bundle where the React namespace
 * interop breaks (`createContext is not a function`) under Turbopack,
 * taking out page-data collection for every route that touches the icon.
 *
 * By isolating every phosphor import behind this `"use client"` module, the
 * server bundle only ever sees a client-component reference and never
 * evaluates phosphor's module scope - the icons render via the client SSR
 * path. This mirrors the credit-icons.tsx / integrations-icons.tsx pattern
 * but centralizes the icons shared across the remaining server detail pages
 * (parties, kyc, documents, tasks, interactions, modeling).
 *
 * Names are re-exported unchanged so server pages only swap their import
 * path; call sites keep `<ArrowLeft weight="light" />` per the design system.
 */
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDown,
  ArrowUp,
  ArrowsLeftRight,
  At,
  Bell,
  Briefcase,
  Buildings,
  CalendarBlank,
  Calculator,
  CaretDown,
  CaretRight,
  CaretUp,
  Chats,
  ChatCircle,
  ChartBar,
  ChartLineUp,
  Check,
  CheckCircle,
  Circle,
  Clock,
  CoinVertical,
  Coins,
  Crosshair,
  CurrencyInr,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  FileText,
  Fingerprint,
  Flag,
  Funnel,
  Gear,
  Graph,
  Handshake,
  Hash,
  House,
  IdentificationCard,
  Info,
  Lightning,
  Link,
  LinkBreak,
  List,
  ListChecks,
  LockSimple,
  MagnifyingGlass,
  MapPin,
  Minus,
  PencilSimple,
  Phone,
  PiggyBank,
  Plus,
  PresentationChart,
  Question,
  Scales,
  SealCheck,
  SealWarning,
  ShieldCheck,
  ShieldWarning,
  SignOut,
  Sparkle,
  Star,
  Tag,
  Target,
  TrashSimple,
  TrendUp,
  TrendDown,
  UploadSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  WhatsappLogo,
  X,
  XCircle,
} from "@phosphor-icons/react";

export {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDown,
  ArrowUp,
  ArrowsLeftRight,
  At,
  Bell,
  Briefcase,
  Buildings,
  CalendarBlank,
  Calculator,
  CaretDown,
  CaretRight,
  CaretUp,
  Chats,
  ChatCircle,
  ChartBar,
  ChartLineUp,
  Check,
  CheckCircle,
  Circle,
  Clock,
  CoinVertical,
  Coins,
  Crosshair,
  CurrencyInr,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  FileText,
  Fingerprint,
  Flag,
  Funnel,
  Gear,
  Graph,
  Handshake,
  Hash,
  House,
  IdentificationCard,
  Info,
  Lightning,
  Link,
  LinkBreak,
  List,
  ListChecks,
  LockSimple,
  MagnifyingGlass,
  MapPin,
  Minus,
  PencilSimple,
  Phone,
  PiggyBank,
  Plus,
  PresentationChart,
  Question,
  Scales,
  SealCheck,
  SealWarning,
  ShieldCheck,
  ShieldWarning,
  SignOut,
  Sparkle,
  Star,
  Tag,
  Target,
  TrashSimple,
  TrendUp,
  TrendDown,
  UploadSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  WhatsappLogo,
  X,
  XCircle,
};
